// src/lib/components/SessionTreeDrawer.tsx
import { useAppState } from '$lib/state/app-context';
import { useWsClient } from '$lib/client/use-ws-client';
import { SessionTreeNode } from './SessionTreeNode';
import { Button } from './core/Button';
import { DialogHeader } from './core/DialogHeader';
import { DialogShell } from './core/DialogShell';

export function SessionTreeDrawer() {
	const app = useAppState();
	const client = useWsClient();

	async function clone() {
		if (!client) return;
		try {
			const response = await client.sendCommand('clone');
			if (!response.success)
				app.addToast(response.error ?? 'Unable to clone the active branch.', 'error');
		} catch (error) {
			app.setConnectionError(error instanceof Error ? error.message : String(error));
		}
	}

	if (!app.layout.treeDrawerOpen) return null;

	return (
		<DialogShell kind="drawer" maxWidth="xl" ariaLabel="Session tree">
			<DialogHeader
				title="Session tree"
				description="Browse branches. Continue-in-place is not available over Pi RPC."
				actions={
					<Button variant="muted" size="sm" onClick={() => app.setLayout('treeDrawerOpen', false)}>
						Close
					</Button>
				}
			/>
			<div className="border-b border-slate-200 p-3">
				<Button variant="secondary" size="touch" onClick={() => void clone()}>
					Clone active branch
				</Button>
			</div>
			<div className="min-h-0 flex-1 overflow-y-auto p-3">
				{app.tree.length === 0 && (
					<p className="px-2 py-8 text-center text-sm text-slate-500">No tree data loaded yet.</p>
				)}
				{app.tree.map((node) => {
					const entry =
						typeof node.entry === 'object' && node.entry !== null && !Array.isArray(node.entry)
							? (node.entry as Record<string, unknown>)
							: {};
					return (
						<SessionTreeNode
							key={typeof entry.id === 'string' ? entry.id : JSON.stringify(node)}
							node={node}
							depth={0}
							app={app}
							client={client}
						/>
					);
				})}
			</div>
		</DialogShell>
	);
}

// src/lib/components/SessionTreeDrawer.svelte
<script lang="ts">
	import type { WebAgentWebSocketClient } from '$lib/client/ws-client';
	import type { AppState } from '$lib/state/app-state.svelte';
	import SessionTreeNode from './SessionTreeNode.svelte';
	import Button from './core/Button.svelte';
	import DialogHeader from './core/DialogHeader.svelte';
	import DialogShell from './core/DialogShell.svelte';

	let { app, client }: { app: AppState; client: WebAgentWebSocketClient | undefined } = $props();

	async function clone(): Promise<void> {
		if (!client) return;
		try {
			const response = await client.sendCommand('clone');
			if (!response.success)
				app.addToast(response.error ?? 'Unable to clone the active branch.', 'error');
		} catch (error) {
			app.setConnectionError(error instanceof Error ? error.message : String(error));
		}
	}
</script>

{#if app.layout.treeDrawerOpen}
	<DialogShell kind="drawer" maxWidth="xl" ariaLabel="Session tree">
		<DialogHeader
			title="Session tree"
			description="Browse branches. Continue-in-place is not available over Pi RPC."
		>
			{#snippet actions()}
				<Button variant="muted" size="sm" onclick={() => (app.layout.treeDrawerOpen = false)}
					>Close</Button
				>
			{/snippet}
		</DialogHeader>
		<div class="border-b border-slate-200 p-3">
			<Button variant="secondary" size="touch" onclick={() => void clone()}
				>Clone active branch</Button
			>
		</div>
		<div class="min-h-0 flex-1 overflow-y-auto p-3">
			{#if app.tree.length === 0}<p class="px-2 py-8 text-center text-sm text-slate-500">
					No tree data loaded yet.
				</p>{/if}{#each app.tree as node (typeof node.entry === 'object' && node.entry !== null && !Array.isArray(node.entry) && typeof (node.entry as Record<string, unknown>).id === 'string' ? (node.entry as Record<string, unknown>).id : JSON.stringify(node))}<SessionTreeNode
					{node}
					depth={0}
					{app}
					{client}
				/>{/each}
		</div>
	</DialogShell>
{/if}
