// src/lib/components/ThinkingDialog.svelte
<script lang="ts">
	import type { WebAgentWebSocketClient } from '$lib/client/ws-client';
	import type { AppState } from '$lib/state/app-state.svelte';
	import Button from './core/Button.svelte';
	import DialogHeader from './core/DialogHeader.svelte';
	import DialogShell from './core/DialogShell.svelte';

	const defaultLevels = ['off', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'];
	let { app, client }: { app: AppState; client: WebAgentWebSocketClient | undefined } = $props();
	let selecting = $state<string | undefined>(undefined);
	let levels = $derived.by(() => {
		const model = app.sessionState?.model;
		const map =
			model && typeof model === 'object' && !Array.isArray(model)
				? model.thinkingLevelMap
				: undefined;
		if (!map || typeof map !== 'object' || Array.isArray(map)) return defaultLevels;
		const supported = defaultLevels.filter((level) => map[level] !== null);
		return supported.length > 0 ? supported : defaultLevels;
	});

	async function choose(level: string): Promise<void> {
		if (!client) return;
		selecting = level;
		try {
			const response = await client.sendCommand('set_thinking_level', { level });
			if (response.success) {
				app.layout.thinkingDialogOpen = false;
				await client.sendCommand('get_state');
			} else app.addToast(response.error ?? 'Pi rejected that thinking level.', 'error');
		} catch (error) {
			app.setConnectionError(error instanceof Error ? error.message : String(error));
		} finally {
			selecting = undefined;
		}
	}
</script>

{#if app.layout.thinkingDialogOpen}
	<DialogShell maxWidth="md" ariaLabel="Thinking level">
		<DialogHeader
			title="Thinking level"
			description="Pi may reject levels unsupported by the active model."
		>
			{#snippet actions()}
				<Button variant="muted" size="sm" onclick={() => (app.layout.thinkingDialogOpen = false)}
					>Close</Button
				>
			{/snippet}
		</DialogHeader>
		<div class="grid gap-1 p-3">
			{#each levels as level (level)}<button
					type="button"
					class={`min-h-11 rounded-lg px-3 text-left text-sm focus:ring-2 focus:ring-blue-500 focus:outline-none ${app.footer.thinking === level ? 'bg-blue-50 font-semibold text-blue-800' : 'text-slate-800 hover:bg-slate-100'}`}
					onclick={() => void choose(level)}
					disabled={selecting !== undefined}>{selecting === level ? 'Applying…' : level}</button
				>{/each}
		</div>
	</DialogShell>
{/if}

// src/lib/components/ThinkingDialog.tsx
import { useState } from 'react';
import { useAppState } from '$lib/state/app-context';
import { useWsClient } from '$lib/client/use-ws-client';
import { Button } from './core/Button';
import { DialogHeader } from './core/DialogHeader';
import { DialogShell } from './core/DialogShell';

const defaultLevels = ['off', 'minimal', 'low', 'medium', 'high', 'xhigh', 'max'];

export function ThinkingDialog() {
	const app = useAppState();
	const client = useWsClient();
	const [selecting, setSelecting] = useState<string | undefined>(undefined);

	const levels = (() => {
		const model = app.sessionState?.model;
		const map =
			model && typeof model === 'object' && !Array.isArray(model)
				? (model as Record<string, unknown>).thinkingLevelMap
				: undefined;
		if (!map || typeof map !== 'object' || Array.isArray(map)) return defaultLevels;
		const supported = defaultLevels.filter(
			(level) => (map as Record<string, unknown>)[level] !== null
		);
		return supported.length > 0 ? supported : defaultLevels;
	})();

	async function choose(level: string) {
		if (!client) return;
		setSelecting(level);
		try {
			const response = await client.sendCommand('set_thinking_level', { level });
			if (response.success) {
				app.setLayout('thinkingDialogOpen', false);
				await client.sendCommand('get_state');
			} else app.addToast(response.error ?? 'Pi rejected that thinking level.', 'error');
		} catch (error) {
			app.setConnectionError(error instanceof Error ? error.message : String(error));
		} finally {
			setSelecting(undefined);
		}
	}

	if (!app.layout.thinkingDialogOpen) return null;

	return (
		<DialogShell maxWidth="md" ariaLabel="Thinking level">
			<DialogHeader
				title="Thinking level"
				description="Pi may reject levels unsupported by the active model."
				actions={
					<Button
						variant="muted"
						size="sm"
						onClick={() => app.setLayout('thinkingDialogOpen', false)}
					>
						Close
					</Button>
				}
			/>
			<div className="grid gap-1 p-3">
				{levels.map((level) => (
					<button
						key={level}
						type="button"
						className={`min-h-11 rounded-lg px-3 text-left text-sm focus:ring-2 focus:ring-blue-500 focus:outline-none ${app.footer.thinking === level ? 'bg-blue-50 font-semibold text-blue-800' : 'text-slate-800 hover:bg-slate-100'}`}
						onClick={() => void choose(level)}
						disabled={selecting !== undefined}
					>
						{selecting === level ? 'Applying…' : level}
					</button>
				))}
			</div>
		</DialogShell>
	);
}
